openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
tags:
  - name: user
paths:
  /users:
    get:
      tags:
        - user
      responses:
        "200":
          description: OK

  /users/login:
    post:
      tags:
        - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
  /users/secret:
    get:
      security:
        - ApiKeyAuth: []

      tags:
        - user
      responses:
        "200":
          description: OK
  /users/secret2:
    get:
      security:
        - ApiKeyAuth: []
      tags:
        - user
      responses:
        "200":
          description: OK

components:
  securitySchemes:
    # BearerAuth:
    #   type: http
    #   scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  # /param:
  #   get:
  #     parameters:
  #       - name: "id"
  #         in: "query"
  #         required: true
  #     responses:
  #       "200":
  #         description: OK
  # /post:
  #   post:
  #     tags:
  #       - "test"
  #     requestBody:
  #       content:
  #         application/x-www-form-urlencoded:
  #           schema:
  #             type: object
  #             properties:
  #               id:
  #                 type: string
  #     responses:
  #       "200":
  #         description: OK
