openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
tags:
  - name: user
paths:
  /user:
    get:
      responses:
        "200":
          description: OK
  # /param:
  #   get:
  #     parameters:
  #       - name: "id"
  #         in: "query"
  #         required: true
  #     responses:
  #       "200":
  #         description: OK
  # /post:
  #   post:
  #     tags:
  #       - "test"
  #     requestBody:
  #       content:
  #         application/x-www-form-urlencoded:
  #           schema:
  #             type: object
  #             properties:
  #               id:
  #                 type: string
  #     responses:
  #       "200":
  #         description: OK
